#!/bin/bash
cd /bin ;
git clone https://github.com/nachorivas581/BOT.git ;
sleep 1 ;
cd BOT/BOT_ADM/request ;
cp botrun /bin ;
cp gfmenu /bin ;
cp gfstart /bin ;
cp gfstop /bin ;
cp gfrest /bin ;
cp gfclear /bin ;
cd /bin ;
chmod 777 *;
echo "Instalacion completa!"
echo "Ejecuta botrun!"
