#!/bin/bash

echo "Escribe el TOKEN de tu BOT:"

read TOKEN
case $TOKEN in

*)  cd /bin/BOT/BOT_ADM/BOT_VPSMOD ; nohup batbot.sh - $TOKEN -c 0 > /dev/null 2>&1 ;sleep 2;  echo " Bot Activado"  ; cd /home/ ; clear

;;
esac

