#!/bin/bash


#COMANDOS


mine_port () {
unset portas
portas_var=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND" | grep "LISTEN")
i=0
while read port; do
var1=$(echo $port | awk '{print $1}') && var2=$(echo $port | awk '{print $9}' | awk -F ":" '{print $2}')
[[ "$(echo -e ${portas[@]}|grep "$var1 $var2")" ]] || {
    portas[$i]="$var1
      $var2"
    let i++
    }
done <<< "$portas_var"
for((i=0; i<=${#portas[@]}; i++)); do
servico="$(echo ${portas[$i]}|cut -d' ' -f1)"
porta="$(echo ${portas[$i]}|cut -d' ' -f2)"
[[ -z $servico ]] && break
texto="${servico}: ${porta}"
     while [[ ${#texto} -lt 35 ]]; do
        texto=$texto" "
     done
echo -ne "${texto}"
let i++
servico="$(echo ${portas[$i]}|cut -d' ' -f1)"
porta="$(echo ${portas[$i]}|cut -d' ' -f2)"
[[ -z $servico ]] && {
   echo -e " "
   break
   }
texto="${servico}:${porta}"
     while [[ ${#texto} -lt 35 ]]; do
        texto=$texto" "
     done
echo -ne "${texto}"
let i++
servico="$(echo ${portas[$i]}|cut -d' ' -f1)"
porta="$(echo ${portas[$i]}|cut -d' ' -f2)"
[[ -z $servico ]] && {
   echo -e " "
   break
   }
texto="${servico}:${porta}"
     while [[ ${#texto} -lt 35 ]]; do
        texto=$texto" "
     done
echo -e "${texto}"
done
}


udp()
{
a="$(systemctl is-active udp-custom)"

case $a  in

active) echo  "[ON]"|lolcat
;;
inactive)echo "[OFF]"|lolcat
;;
esac
}





# Nexuser
SSH="$(grep -c ".*" /etc/usuarios)"

if [ "$1" = "root" ]
then
echo "<h2>Usuario invalido !</h2>"
exit
fi

limite=$(cat /etc/usuarios | wc -l)

if [ "$limite" -gt "41" ]
then
echo "Limite de Cuentas Excedido!"
exit 0
fi

#CONFIGURACIONES:
ip="$(curl ifconfig.me)"
validade=$(date '+%C%y/%m/%d' -d " +2 days")
validadebr=$(date '+%d/%m/%C%y' -d " +2 days")
a="$(udp)"
sudo useradd -M -s /bin/false $1 -e $validade

(echo $2 ; echo $2) | passwd $1

echo "$1 : $2  IP: $ip" >> /etc/usuarios

echo            "SSH[VPS-MOD]"
echo "----------------------------------"
echo "Cuentas creadas:  [$SSH]"
echo "✔Cuenta Creada Con Exito!✔"
echo "⏱Hora de Creacion": $(printf '%(%H:%M:%S)T')
echo "----------------------------------"
echo "👤Usuario: $1"

echo "🔑 Contraseña: $2"

echo "⏱ Vencimiento: $validadebr❌"
echo "----------------------------------"
echo "👉IP: $ip"
echo "-----------------------------------"
echo "Puertos Activos:"
mine_port
echo UDP-STATUS : $a
echo "UDP-PORT : 1-65535"

echo "----------------------------------"
