#! /bin/bash


#PRUEBA
ABOUTME=`curl -s "https://api.telegram.org/bot/getUpdates"`
if [[ "$ABOUTME" =~ \"ok\"\:true\, ]]; then
        if [[ "$ABOUTME" =~ \"username\"\:\"([^\"]+)\" ]]; then
                MYUSERNAME=${BASH_REMATCH[1]}
                
        fi

        if [[ "$ABOUTME" =~ \"first_name\"\:\"([^\"]+)\" ]]; then
                MYFIRSTNAME=${BASH_REMATCH[1]}
                
        fi

        if [[ "$ABOUTME" =~ \"id\"\:([0-9\-]+), ]]; then
                
                BOTID=${BASH_REMATCH[1]};
        fi

else
        echo "Error: maybe wrong token... exit.";
        exit;
fi




#COMANDOS

status="$(php /var/www/html/status)"
ID="$BOTID"
Usuario="$MYUSERNAME"
Nombre="$MYFIRSTNAME"

(echo "
𝙱𝚒𝚎𝚗𝚟𝚎𝚗𝚒𝚍𝚘 ! $Nombre

Tu Usuario: @$Usuario

Tu ID: $ID

======🚫 Tus comandos Disponibles=========
Status Server [GRAND-FANTASIA]: [$status]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
/start ❈ INICIAR  SERVIDOR  GF|
/stop ❈ PARAR SERVIDOR GF |
/restart ❈ RESETEAR SERVIDOR GF |
/clear  ❈ BORRAR CACHE DEL SERVIDOR [GF-SERVER] |
/menu ❈ Ver el menu nuevamente[GF-SERVER] |
/exit ❈ Salir del Bot |
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••")
