#! /bin/bash


#PRUEBA

#COMANDOS

status="$(php /var/www/html/status)"

(echo "

======🚫 Tus comandos Disponibles=========
Status Server [GRAND-FANTASIA]: [$status]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
/start ❈ INICIAR  SERVIDOR  GF|
/stop ❈ PARAR SERVIDOR GF |
/restart ❈ RESETEAR SERVIDOR GF |
/clear  ❈ BORRAR CACHE DEL SERVIDOR [GF-SERVER] |
/menu ❈ Ver el menu nuevamente[GF-SERVER] |
/exit ❈ Salir del Bot |
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••")
