#! /bin/bash

#COMANDOSID
ABOUTME=`curl -s "https://api.telegram.org/bot2037980112:AAGx5MQlBYS-FWSVBqvPjSd-dX0R9Unr1y8/getUpdates"`
if [[ "$ABOUTME" =~ \"ok\"\:true\, ]]; then
        if [[ "$ABOUTME" =~ \"username\"\:\"([^\"]+)\" ]]; then
                MYUSERNAME=${BASH_REMATCH[1]}

        fi

        if [[ "$ABOUTME" =~ \"first_name\"\:\"([^\"]+)\" ]]; then
                MYFIRSTNAME=${BASH_REMATCH[1]}

        fi

        if [[ "$ABOUTME" =~ \"id\"\:([0-9\-]+), ]]; then

                BOTID=${BASH_REMATCH[1]};
        fi

else
        echo "Error: maybe wrong token... exit.";
        exit;
fi




#COMANDOS
key_tmp="VPS-MOD:#!Nex$RANDOM@$RANDOM@$RANDOM!"
a="VPS-MOD"
b="Nex$RANDOM@$RANDOM@$RANDOM!"
echo "$a" > /tmp/a
echo "$b" > /tmp/b
pasta1=$(cat /tmp/a)
pasta2=$(cat /tmp/b)
signus=":"
key="$(cd /var/www/html/VPS-MOD ; ls | wc -l)"
mkdir /var/www/$pasta1
mkdir /var/www/html/$pasta1
mkdir /var/www/html/$pasta1/$pasta2
touch /home/keyssh/$client
cp /home/list /var/www/html/$pasta1/$pasta2/list

(echo "
       🔑🔑🔑 GENERADOR KEYS [VPS-MOD]🔑🔑🔑
•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
   ✅ Key Exitosa! ✅
   Hora:$(printf '%(%H:%M:%S)T')
 ⚠️ Autodestruccion en 24 Horas ⚠️
    🔑  Keys Generadas: [$key]🔑
     Contacto: @Nachoeivas
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
   ⚠️ Script    [VPS-MOD] ⚠️
  🛡️ KEY OFICIAL 🛡️ : Nexuser Creador
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
 💥 KEY: 💥
 $pasta1:$pasta2
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
  🛡️  INSTALADOR OFICIAL !
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
apt update -y; apt upgrade -y; wget https://raw.githubusercontent.com/nachorivas581/Nexuser/main/inst; chmod 777 inst; ./inst
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
  Soporte : Ubuntu 14.04 - 16.04 - 18.04 - 20.04
     SO Recomendado: Ubuntu 18.04
  🛡️⚔️ Key Generada 🛡️⚔️")











 (echo "
       🔑🔑🔑 GENERADOR KEYS [VPS-MOD]🔑🔑🔑
•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
   ✅ Key Exitosa! ✅
   Hora:$(printf '%(%H:%M:%S)T')
 ⚠️ Autodestruccion en 24 Horas ⚠️
    🔑  Keys Generadas: [$key]🔑
     Contacto: @Nachoeivas
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
   ⚠️ Script    [VPS-MOD] ⚠️
  🛡️ KEY OFICIAL 🛡️ : Nexuser Creador
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
 💥 KEY: 💥
 $pasta1:$pasta2
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
  🛡️  INSTALADOR OFICIAL !
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
apt update -y; apt upgrade -y; wget https://raw.githubusercontent.com/nachorivas581/Nexuser/main/inst; chmod 777 inst; ./inst
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
  Soporte : Ubuntu 14.04 - 16.04 - 18.04 - 20.04
     SO Recomendado: Ubuntu 18.04
  🛡️⚔️ Key Generada 🛡️⚔️") >>  $pasta1:$pasta2.txt

curl -s -X POST https://api.telegram.org/bot2037980112:AAGx5MQlBYS-FWSVBqvPjSd-dX0R9Unr1y8/sendDocument -F chat_id="$BOTID" -F document="@/bin/BOT/BOT_ADM/BOT_VPSMOD/$pasta1:$pasta2.txt" >/dev/null

cd /bin/BOT/BOT_ADM/BOT_VPSMOD
rm -r $pasta1:$pasta2.txt
