#! /bin/bash
udp()
{
a="$(systemctl is-active udp-custom)"

case $a  in

active) echo  "UDP-STATUS:[ON]"|lolcat
;;
inactive)echo "UDP-STATUS:[OFF]"|lolcat
;;
esac
}

hys()
{
a="$(systemctl is-active hysteria-server)"

case $a  in

active) echo  "Hysteria:[ON]"|lolcat
;;
inactive)echo "Hysteria:[OFF]"|lolcat
;;
esac
}





statusbadvpn()
{
on="[ON]" && off="[OFF]"
[[ $(ps x | grep badvpn | grep -v grep | awk '{print $1}') ]] && badvpn=$on || badvpn=$off
echo "BADVPN:" "$badvpn"|lolcat

}

mine_port () {
unset portas
portas_var=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND" | grep "LISTEN")
i=0
while read port; do
var1=$(echo $port | awk '{print $1}') && var2=$(echo $port | awk '{print $9}' | awk -F ":" '{print $2}')
[[ "$(echo -e ${portas[@]}|grep "$var1 $var2")" ]] || {
    portas[$i]="$var1
      $var2"
    let i++
    }
done <<< "$portas_var"
for((i=0; i<=${#portas[@]}; i++)); do
servico="$(echo ${portas[$i]}|cut -d' ' -f1)"
porta="$(echo ${portas[$i]}|cut -d' ' -f2)"
[[ -z $servico ]] && break
texto="${servico}: ${porta}"
     while [[ ${#texto} -lt 35 ]]; do
        texto=$texto" "
     done
echo -ne "${texto}"
let i++
servico="$(echo ${portas[$i]}|cut -d' ' -f1)"
porta="$(echo ${portas[$i]}|cut -d' ' -f2)"
[[ -z $servico ]] && {
   echo -e " "
   break
   }
texto="${servico}:${porta}"
     while [[ ${#texto} -lt 35 ]]; do
        texto=$texto" "
     done
echo -ne "${texto}"
let i++
servico="$(echo ${portas[$i]}|cut -d' ' -f1)"
porta="$(echo ${portas[$i]}|cut -d' ' -f2)"
[[ -z $servico ]] && {
   echo -e " "
   break
   }
texto="${servico}:${porta}"
     while [[ ${#texto} -lt 35 ]]; do
        texto=$texto" "
     done
echo -e "${texto}"
done
}



#COMANDOS

SSH="$(grep -c ".*" /etc/usuarios)"
status="$(systemctl is-active apache2)"
ID="$BOTID"
Usuario="$MYUSERNAME"
Nombre="$MYFIRSTNAME"
udp="$(udp)"
hys="$(hys)"
statusbadvpn="$(statusbadvpn)"
mine_port="$(mine_port)"
IP="$(curl ifconfig.me)
(echo "
𝙱𝚒𝚎𝚗𝚟𝚎𝚗𝚒𝚍𝚘 al Menu BOT [VPS-MOD]

======🚫 Tus comandos Disponibles [VPS-MOD]🚫=========
 👤 SSH Generadas [$SSH]
 👉$udp
 👉$hys
 👉$statusbadvpn
 👉$mine_port
  👉$IP

 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
🔐|/key|❈ 🔑🔑🔑Generar Key  [VPS-MOD]🔑🔑🔑 |
------------------------------------------------------
✅|/onudp| ❈ Activar UDP [VPS-MOD] |
💥|/offudp| ❈ Apagar UDP [VPS-MOD] |
------------------------------------------------------
✅|/onbad | ❈Activar BADVPN  [VPS-MOD] |
💥|/offbad|❈Apagar BADVPN  [VPS-MOD] |
------------------------------------------------------
✅|/python101| ❈Activar Python(Response 101)  [VPS-MOD] |
💥|/off101| ❈ Apagar Python(Response 101)  [VPS-MOD] |
------------------------------------------------------
✅|/onpsi| ❈ Activar Psiphon [VPS-MOD] |
💥|/offpsi| ❈ Apagar Psiphon [VPS-MOD] |
✏|/datpsi| ❈Datos Psiphon  [VPS-MOD] |
------------------------------------------------------
👤|/ssh|  ❈ Crear Cuenta SSH[VPS-MOD] |
✏|/infssh| ❈Ver Cuentas SSH  [VPS-MOD] |
------------------------------------------------------
⚡|/fast| ❈ Ver Velocidad del Servidor [VPS-MOD] |
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
     🔧🔧🔧🔧🔧ADQUIERE TU BOT-ADM 🔧🔧🔧🔧🔧🔧
      💥💥💥Contacto @Nachorivasc💥💥💥       ")
