#! /bin/bash


#PRUEBA
ABOUTME=`curl -s "https://api.telegram.org/bot(token)/getUpdates"`
if [[ "$ABOUTME" =~ \"ok\"\:true\, ]]; then
        if [[ "$ABOUTME" =~ \"username\"\:\"([^\"]+)\" ]]; then
                MYUSERNAME=${BASH_REMATCH[1]}

        fi

        if [[ "$ABOUTME" =~ \"first_name\"\:\"([^\"]+)\" ]]; then
                MYFIRSTNAME=${BASH_REMATCH[1]}

        fi

        if [[ "$ABOUTME" =~ \"id\"\:([0-9\-]+), ]]; then

                BOTID=${BASH_REMATCH[1]};
        fi

else
        echo "Error: maybe wrong token... exit.";
        exit;
fi

udp()
{
a="$(systemctl is-active udp-custom)"

case $a  in

active) echo  "UDP-STATUS:[ON]"|lolcat
;;
inactive)echo "UDP-STATUS:[OFF]"|lolcat
;;
esac
}

statusbadvpn()
{
on="\033[1;32m[ON]" && off="\033[1;31m[OFF]"
[[ $(ps x | grep badvpn | grep -v grep | awk '{print $1}') ]] && badvpn=$on || badvpn=$off
echo -e "\e[1;31mBADVPN:\e[0m" "$badvpn"|lolcat

}



#COMANDOS

SSH="$(grep -c ".*" /etc/usuarios)"
status="$(systemctl is-active apache2)"
ID="$BOTID"
Usuario="$MYUSERNAME"
Nombre="$MYFIRSTNAME"
udp="$(udp)"
statusbadvpn="$(statusbadvpn)
(echo "
𝙱𝚒𝚎𝚗𝚟𝚎𝚗𝚒𝚍𝚘 ! $Nombre

Tu Usuario: @$Usuario

Tu ID: $ID

======🚫 Tus comandos Disponibles [VPS-MOD]=========
Status Generador [VPS-MOD]: [$status]
 SSH Generadas [$SSH]
 $udp
 $statusbadvpn
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
/onudp ❈ Activar UDP [VPS-MOD] |
/offudp ❈ Apagar UDP [VPS-MOD] |
/onbad  ❈Activar BADVPN  [VPS-MOD] |
/offbad  ❈Apagar BADVPN  [VPS-MOD] |
/onpsi ❈ Activar Psiphon [VPS-MOD] |
/datpsi ❈Datos Psiphon  [VPS-MOD] |
/ssh  ❈ Crear Cuenta SSH[VPS-MOD] |
/infssh ❈Ver Cuentas SSH  [VPS-MOD] |
/exit ❈ Salir del Bot |
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••")
