#! /bin/bash
#COMANDOS


key="$(cd /var/www/html/VPS-MOD ; ls | wc -l)"
status="$(systemctl is-active apache2)"
ID="$BOTID"
Usuario="$MYUSERNAME"
Nombre="$MYFIRSTNAME"
SSH="$(grep -c ".*" /etc/usuarios)"

(echo "
𝙱𝚒𝚎𝚗𝚟𝚎𝚗𝚒𝚍𝚘 ! 
======🚫 Tus comandos Disponibles=========
Status Generador [VPS-MOD]: [$status]
 Keys Generadas [$key]
 SSH Generadas [$SSH]
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
/infosys ❈ INFORMACION DEL SERVIDOR |
/instal ❈ INSTALADOR OFICIAL |
/keygen ❈ Generar Keys [VPS-MOD] |
/ssh    ❈ Generar Cuenta SSH [VPS-MOD] |
/fast  ❈ Ver Velocidad del Servidor [VPS-MOD] |
/exit ❈ Salir del Bot |
 ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••")
